djangoMysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    AboutView

)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('about/', AboutView.as_view(), name='about')
]

mainapp/models.py
#import sys
from PIL import Image
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.utils import timezone
#from django.core.files.uploadedfile import InMemoryUploadedFile
#from io import BytesIO

User = get_user_model()

def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]

def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})

class MinResolutionErrorException(Exception):
    pass

class MaxResolutionErrorException(Exception):
    pass

class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to, reverse=True)
                    )
        return products

class LatestProducts:

    objects = LatestProductsManager()

class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Диваны': 'sofa__count',
        'Стулья': 'chair__count',
        'Пуфики': 'puf__count',
        'Кровати': 'bed__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_sidebar(self):
        models = get_models_for_count('sofa', 'chair', 'puf', 'bed')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolut_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data

class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

class Product(models.Model):

    MIN_RESOLUTION = (200, 200)
    MAX_RESOLUTION = (2500, 2500)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        min_width, min_height = self.MIN_RESOLUTION
        max_width, max_height = self.MAX_RESOLUTION
        if img.width < min_width or img.height < min_height:
            raise MinResolutionErrorException('Разрешение изображения меньше минимального!')
        if img.width > max_width or img.height > max_height:
            raise MaxResolutionErrorException('Разрешение изображения больше максимальног!')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Chair(Product):

    size = models.CharField(max_length=255, verbose_name='Размеры (ДхГхВ)')
    frame_material = models.CharField(max_length=255, verbose_name='Материал каркаса')
    filling_the_bed = models.CharField(max_length=255, verbose_name='Наполнение спального (посадочного) места')
    support_material = models.CharField(max_length=255, verbose_name='Материал опор')
    upholstery_material = models.CharField(max_length=255, verbose_name='Материал обивки')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolut_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name

class Puf(Product):

    size = models.CharField(max_length=255, verbose_name='Размеры (ДхГхВ)')
    frame_material = models.CharField(max_length=255, verbose_name='Материал каркаса')
    filling_the_bed = models.CharField(max_length=255, verbose_name='Наполнение спального (посадочного) места')
    support_material = models.CharField(max_length=255, verbose_name='Материал опор')
    upholstery_material = models.CharField(max_length=255, verbose_name='Материал обивки')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolut_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name

class Bed(Product):

    size = models.CharField(max_length=255, verbose_name='Размеры (ШхДхВ)')
    bed_size = models.CharField(max_length=255, verbose_name='Размеры спального места (ШхД)')
    frame_material = models.CharField(max_length=255, verbose_name='Материал каркаса')
    support_material = models.CharField(max_length=255, verbose_name='Материал опор')
    upholstery_material = models.CharField(max_length=255, verbose_name='Материал обивки')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolut_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name

class Sofa(Product):


    size = models.CharField(max_length=255, verbose_name='Размеры (ДхГхВ)')
    bed = models.BooleanField(default=True, verbose_name='Наличие спального места')
    bed_size = models.CharField(max_length=255, null=True, blank=True, verbose_name='Размеры спального места (ДхГ)')
    frame_material = models.CharField(max_length=255, verbose_name='Материал каркаса')
    filling_the_bed = models.CharField(max_length=255, verbose_name='Наполнение спального (посадочного) места')
    support_material = models.CharField(max_length=255, verbose_name='Материал опор')
    upholstery_material = models.CharField(max_length=255, verbose_name='Материал обивки')
    transformation_mechanism = models.CharField(max_length=255, verbose_name='Механизм трансформации')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolut_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name



class CartProduct(models.Model):

    user = models.ForeignKey('Customer', null=True, verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonimous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Заказчик', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)

templates/about.html
{% extends 'base.html' %}
{% block content %}

<section class="py-5 vh-100" style="background-image: url('../media/1.jpg'); background-size: 100% 100%; filter: brightness(70%);">
        <div class="container px-4 px-lg-5 mt-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Магазин мягкой мебели</h1>
                    <p class="lead fw-normal text-white-50 mb-0">В нашем интернет-магазине представлены только тщательно
                    отобранные модели, исключительные диваны – хиты продаж. Каждая модель дивана из нашего интернет каталога
                    – это воплощение отличного дизайна, легенда мебельной отрасли.</p>
                </div>
        </div>
</section>

{% endblock content %}

templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($){
        $('#id_bed').on('click',function () {
            if($('#id_bed').prop('checked') == true){
                $('#id_bed_size').prop('readonly', false)
                $('#id_bed_size').val('')
                $('#id_bed_size').css('background', 'white')
            }else {
                $('#id_bed_size').prop('readonly', true)
                $('#id_bed_size').val('&#8212;')
                $('#id_bed_size').css('background', 'lightgray')
            }
        })
    })(django.jQuery);
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" href="../media/favicon.png" type="image/png">
    <!-- Bootstrap icons-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Core theme CSS (includes Bootstrap)-->

</head>
<body>
<!-- Navigation-->

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'base' %}">Мягкая мебель</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'base' %}">Главная</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">О нас</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{{ category.url }}" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Каталог</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <li><a class="dropdown-item" href="{{ category.url }}">{{ category.name }}
                                ({{ category.count }})</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'cart' %}">
                <button class="btn btn-outline-dark" type="submit" href="{% url 'cart' %}">
                    <i class="bi-cart-fill me-1"></i>
                    Корзина
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.total_products }}</span>
                </button>
            </form>
        </div>
    </div>
</nav>
<!-- Header-->
{% block content %}
<header class="bg-body py-5" style="background-image: url('../media/home-banner.jpg');">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Магазин мягкой мебели</h1>
            <p class="lead fw-normal text-white-50 mb-0">В нашем интернет-магазине представлены только тщательно
                отобранные модели, исключительные диваны – хиты продаж. Каждая модель дивана из нашего интернет каталога
                – это воплощение отличного дизайна, легенда мебельной отрасли.</p>
        </div>
    </div>

</header>
<!-- Section-->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}

                    <div class="col mb-5">

                        <div class="card h-100">

                            <!-- Sale badge-->
                            <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                Sale
                            </div>
                            <div class="text-center"><a class="btn btn-outline-secondary mt-auto"
                                                            href="{{ product.get_absolut_url }}">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="...">

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder" href="{{ product.get_absolute_url }}">{{ product.title }}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">

                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    {{ product.price }} руб.
                                </div>

                            </div>
                            </a></div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                                    В корзину</a></div>
                            </div>

                        </div>

                    </div>

                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright © Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
<!-- Core theme JS-->


</body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid" alt=""></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>
              <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
                  {% csrf_token %}
                  <input type="number" class="form-control" name="qty" style="width: 70px" min="1" value="{{ item.qty }}">
                  <br>
                  <input type="submit" class="btn btn-primary" value="Изменить кол-во">
              </form>
          </td>
          <td>{{ item.final_price }} руб.</td>
          <td>
              <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
          </td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
        </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container px-4 px-lg-3 my-3">
        <nav aria-label="breadcrumb" class="mt-3">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
                <li class="breadcrumb-item">{{ category.name }}</li>
            </ol>
        </nav>

        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in category_products %}
                <div class="col mb-5">

                    <div class="card h-100">

                        <!-- Sale badge-->
                        <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                            Sale
                        </div>
                        <div class="text-center"><a class="btn btn-outline-secondary mt-auto"
                                                    href="{{ product.get_absolut_url }}">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="...">

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder" href="{{ product.get_absolute_url }}">{{ product.title }}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">

                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    {{ product.price }} руб.
                                </div>

                            </div>
                        </a></div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                        href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                                В корзину</a></div>
                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/chair_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Размеры (ДхГхВ)</td>
      <td>{{ product.size }}</td>
    </tr>
    <tr>
      <td>Материал каркаса</td>
      <td>{{ product.frame_material }}</td>
    </tr>
    <tr>
      <td>Наполнение спального (посадочного) места</td>
      <td>{{ product.filling_the_bed }}</td>
    </tr>
    <tr>
      <td>Материал опор</td>
      <td>{{ product.support_material }}</td>
    </tr>
    <tr>
      <td>Материал обивки</td>
      <td>{{ product.upholstery_material }}</td>
    </tr>
  </tbody>
</table>

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container px-4 px-lg-3 my-3">
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid" alt=""></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>{{ item.qty }}</td>
          <td>{{ item.final_price }} руб.</td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
        </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
</form>
</div>

{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}


    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <style>
                    .scale {
                        transition: 1s; /* Время эффекта */
                    }

                    .scale:hover {
                        transform: scale(1.5); /* Увеличиваем масштаб */
                    }
                </style>
                <div class="col-md-6"><img src="{{ product.image.url }}" class="card-img-top mb-5 mb-md-0 scale"
                                           alt="..."></div>
                <div class="col-md-6">
                    <h1 class="display-5 fw-bolder">{{ product.title }}</h1>
                    <div class="fs-5 mb-5">
                        <span> {{ product.price }} руб.</span>
                    </div>
                    <p class="lead">Описание: {{ product.description }} </p>
                    <p>Характеристики:</p>
                    {{ product|product_spec }}
                    <div class="d-flex">
                        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}">
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                <i class="bi-cart-fill me-1"></i>
                                Добавить в корзину
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}

templates/puf_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Размеры (ДхГхВ)</td>
      <td>{{ product.size }}</td>
    </tr>
    <tr>
      <td>Материал каркаса</td>
      <td>{{ product.frame_material }}</td>
    </tr>
    <tr>
      <td>Наполнение спального (посадочного) места</td>
      <td>{{ product.filling_the_bed }}</td>
    </tr>
    <tr>
      <td>Материал опор</td>
      <td>{{ product.support_material }}</td>
    </tr>
    <tr>
      <td>Материал обивки</td>
      <td>{{ product.upholstery_material }}</td>
    </tr>
  </tbody>
</table>